version: '3.8'

services:
  api:
    build: .
    container_name: server-for-filmari
    ports:
      - "8888:8000"
    volumes:
      - ./collections.db:/app/collections.db
    restart: unless-stopped